AWSTemplateFormatVersion: '2010-09-09'
Description: 'Fortnite Standings Thin WebService

  '
Globals:
  Function:
    Environment:
      Variables:
        ClientId: 3wzomqpieq4jiyl0ivzjd2ajrewp5s
        ExtensionOwnerTwitchId: '79606633'
        ExtensionVersion: 0.0.1
Outputs:
  LambdaFunction:
    Description: Lambda function ARN
    Value:
      Fn::GetAtt:
      - LambdaFunction
      - Arn
Resources:
  DefaultLambdaInvocationRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
        Version: '2012-10-17'
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            - logs:DescribeLogStream
            - cloudwatch:PutMetricData
            - dynamodb:DeleteItem
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:UpdateItem
            - dynamodb:BatchWriteItem
            Effect: Allow
            Resource: '*'
          Version: '2012-10-17'
        PolicyName: LambdaInvocationRolePolicy
    Type: AWS::IAM::Role
  LambdaFunction:
    Properties:
      CodeUri: s3://deployment-us-east-1-lambdas-1/f9f7e52ed321d1f2894258d71bdd8469
      Events:
        FortniteApi:
          Properties:
            Method: ANY
            Path: /{any+}
          Type: Api
      FunctionName: FortniteWCStandingsLambdaFunction
      Handler: io.sengage.webservice.function.RequestHandler
      MemorySize: 320
      Role:
        Fn::GetAtt:
        - DefaultLambdaInvocationRole
        - Arn
      Runtime: java8
      Timeout: 30
    Type: AWS::Serverless::Function
  StandingsTable:
    Properties:
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: WeekRegion
        AttributeType: S
      - AttributeName: Rank
        AttributeType: N
      GlobalSecondaryIndexes:
      - IndexName: WeekRegion-Rank-Index
        KeySchema:
        - AttributeName: WeekRegion
          KeyType: HASH
        - AttributeName: Rank
          KeyType: RANGE
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: '5'
          WriteCapacityUnits: '1'
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: Standings
    Type: AWS::DynamoDB::Table
Transform: AWS::Serverless-2016-10-31
