AWSTemplateFormatVersion: '2010-09-09'
Description: 'Fortnite Standings Thin WebService

  '
Globals:
  Api:
    Cors:
      AllowHeaders: '''Content-Type,X-Amz-Date,Authorization,X-Api-Key,x-requested-with'''
      AllowMethods: '''GET,HEAD,POST,PUT,OPTIONS,PATCH'''
      AllowOrigin: '''*'''
  Function:
    Environment:
      Variables:
        ClientId: 3wzomqpieq4jiyl0ivzjd2ajrewp5s
        ExtensionOwnerTwitchId: '79606633'
        ExtensionVersion: 0.0.4
Outputs:
  LambdaFunction:
    Description: Lambda function ARN
    Value:
      Fn::GetAtt:
      - LambdaFunction
      - Arn
Resources:
  DefaultLambdaInvocationRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
        Version: '2012-10-17'
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            - logs:DescribeLogStream
            - cloudwatch:PutMetricData
            - dynamodb:DeleteItem
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:UpdateItem
            - dynamodb:BatchWriteItem
            Effect: Allow
            Resource: '*'
          Version: '2012-10-17'
        PolicyName: LambdaInvocationRolePolicy
    Type: AWS::IAM::Role
  FeedbackTable:
    Properties:
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: Feedback
    Type: AWS::DynamoDB::Table
  LambdaFunction:
    Properties:
      CodeUri: s3://deployment-us-east-1-lambdas-1/82ef7402be188df97f0e740ea30de93f
      Events:
        FortniteApi:
          Properties:
            Method: ANY
            Path: /{any+}
          Type: Api
      FunctionName: FortniteWCStandingsLambdaFunction
      Handler: io.sengage.webservice.function.RequestHandler
      MemorySize: 320
      Role:
        Fn::GetAtt:
        - DefaultLambdaInvocationRole
        - Arn
      Runtime: java8
      Timeout: 900
    Type: AWS::Serverless::Function
  StandingsTable:
    Properties:
      AttributeDefinitions:
      - AttributeName: WeekRegionName
        AttributeType: S
      - AttributeName: WeekRegion
        AttributeType: S
      - AttributeName: StandingRank
        AttributeType: N
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
      - IndexName: WeekRegion-Rank-Index
        KeySchema:
        - AttributeName: WeekRegion
          KeyType: HASH
        - AttributeName: StandingRank
          KeyType: RANGE
        Projection:
          ProjectionType: ALL
      KeySchema:
      - AttributeName: WeekRegionName
        KeyType: HASH
      TableName: Standings
    Type: AWS::DynamoDB::Table
  StandingsUpdater:
    Properties:
      CodeUri: s3://deployment-us-east-1-lambdas-1/8934ca167076b096cb845190f39a2603
      Events:
        ScheduledUpdateEvent:
          Properties:
            Input: '{ "solos": true, "week": 9, "pause": false }'
            Schedule: rate(5 minutes)
          Type: Schedule
      Handler: standings_updater.handler
      MemorySize: 256
      Role:
        Fn::GetAtt:
        - DefaultLambdaInvocationRole
        - Arn
      Runtime: python3.6
      Timeout: 800
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
