openapi: 3.0.0
info:
  version: "1.0.0"
  title: SengageWebServiceAPI
paths:
  '/{proxy+}':
    x-amazon-apigateway-any-method:
      parameters:
        - name: proxy
          in: path
          required: true
          schema:
            type: string
      responses: {}
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: '200'
        uri: >-
          arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:859597192772:function:SengageWSLambdaFunction/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        credentials: arn:aws:iam::859597192772:role/sengage-webservice-ApiGatewayLambdaInvokePermissio-EOS8J586RPXN
        type: aws_proxy
servers:
  - url: 'https://gy415nuibc.execute-api.us-east-1.amazonaws.com/{basePath}'
    variables:
      basePath:
        default: /v1