AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Fortnite Standings Thin WebService


Globals:
  Api:
    Cors:
      AllowMethods: "'GET,HEAD,POST,PUT,OPTIONS,PATCH'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,x-requested-with'"
      AllowOrigin: "'*'"
  Function:
    Environment:
      Variables:
        ExtensionOwnerTwitchId: "79606633"
        ClientId: "3wzomqpieq4jiyl0ivzjd2ajrewp5s"
        ExtensionVersion: "0.0.4"

Resources:
  StandingsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
      - AttributeName: "WeekRegionName"
        AttributeType: "S"
      - AttributeName: "WeekRegion"
        AttributeType: "S"
      - AttributeName: "StandingRank"
        AttributeType: "N"
      KeySchema:
      - AttributeName: "WeekRegionName"
        KeyType: "HASH"
      TableName: Standings
      GlobalSecondaryIndexes:
        - IndexName: "WeekRegion-Rank-Index"
          KeySchema:
            - AttributeName: WeekRegion
              KeyType: HASH
            - AttributeName: StandingRank
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
  FeedbackTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: "id"
        AttributeType: "S"
      KeySchema:
      - AttributeName: "id"
        KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: Feedback
      
# Http API LAMBDAS
  LambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: io.sengage.webservice.function.RequestHandler
      FunctionName: FortniteWCStandingsLambdaFunction
      Runtime: java8
      Timeout: 900
      MemorySize: 320
      Role: !GetAtt DefaultLambdaInvocationRole.Arn
      CodeUri: ./target/webservice-1.0.0.jar
      Events:
        FortniteApi:
            Type: Api
            Properties:
                Path: /{any+}
                Method: ANY
  #IAM
  DefaultLambdaInvocationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
      - PolicyName: LambdaInvocationRolePolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            - logs:DescribeLogStream
            - cloudwatch:PutMetricData
            - dynamodb:DeleteItem
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:UpdateItem
            - dynamodb:BatchWriteItem
            Resource: "*"

# Worker lambdas
  StandingsUpdater:
    Type: 'AWS::Serverless::Function'
    Properties:
      Timeout: 800
      MemorySize: 256
      CodeUri: ./python/build    
      Handler: standings_updater.handler
      Runtime: python3.6
      Role: !GetAtt DefaultLambdaInvocationRole.Arn
      Events:
        ScheduledUpdateEvent:
          Type: Schedule
          Properties:
              Schedule: rate(5 minutes)
              Input: "{ \"solos\": false, \"week\": 10, \"pause\": false }"


Outputs:
  LambdaFunction:
    Description: "Lambda function ARN"
    Value: !GetAtt LambdaFunction.Arn
    